import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    callback divide-income(string);
    width: 350px;
    height: 400px;

    GridLayout {   
        padding:50px;
        spacing:25px;
        Row{
            Text { 
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row{
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your number here";
                height: 35px;
            }
        }

        Row{
            Button {
                text:"calculate";
                primary: true;
                height: 35px;
                clicked => {divide-income(income.text)}
            }
        }

        Row{
            Rectangle {
                height: 100px;
                background: #f2f2f2;
                Text {
                    color: black;
                    font-size: 16px;
                    font-weight: 500;
                    text: root.results;
                }
            }
        }
    }
}